version: '3.4'

services:
  springbootdevcontainer:
    image: springbootdevcontainer
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development_stage
    ports:
      - 8080:8080
    volumes:
      - .:/workspace:cache
      - vscode-server-cache:/home/vscode/.vscode-server/extensions/
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-server-cache:
